/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.javafx.scene.layout.region.Margins;
import javax.swing.ComboBoxModel;
import dao.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ariel
 * 
 * TODO:
 * Colocar valores a serem editados na classe correspondente; talvez utilizar um event da tabela?
 */

public class form_Main extends javax.swing.JFrame {
    
    private String tabelaCmb;
    private ResultSet resultSet;
    private int id, indexTbl;
    

    private ComboBoxModel<String> tabelasBoxModel;
    private TableModel tableModel;
    
    //Instâncias
    private dao.DAOGames daoGames = new DAOGames();
    private DAOFornecedor daoFornecedor = new DAOFornecedor();
    private DAOMarca daoMarca = new DAOMarca();
    
    public form_Main() {
        initComponents();
        
        cmb_tabelasItemStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jpa_ferramentas = new javax.swing.JPanel();
        cmb_tabelas = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_adicionar = new javax.swing.JButton();
        bnt_editar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tabela = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Games");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(966, 450));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setPreferredSize(new java.awt.Dimension(43, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-rubik's-cube-48.png"))); // NOI18N

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
            .addComponent(jSeparator2)
        );

        cmb_tabelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Games", "Fornecedores", "Marcas" }));
        cmb_tabelas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tabelasItemStateChanged(evt);
            }
        });

        jLabel2.setText("Tabela");

        jLabel3.setText("Ações");

        btn_adicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-plus-24.png"))); // NOI18N
        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        bnt_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-24.png"))); // NOI18N
        bnt_editar.setText("Editar");
        bnt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt_editarActionPerformed(evt);
            }
        });

        btn_remover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-clear-symbol-48.png"))); // NOI18N
        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpa_ferramentasLayout = new javax.swing.GroupLayout(jpa_ferramentas);
        jpa_ferramentas.setLayout(jpa_ferramentasLayout);
        jpa_ferramentasLayout.setHorizontalGroup(
            jpa_ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_ferramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpa_ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1)
                    .addComponent(btn_adicionar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_remover, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnt_editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_tabelas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpa_ferramentasLayout.setVerticalGroup(
            jpa_ferramentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpa_ferramentasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_tabelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_remover, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bnt_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );

        tbl_tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_tabela);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpa_ferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpa_ferramentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Evento com switch responsável por chamar o DAO correspondente de cada tabela
     * @param evt 
     * 
     */
    private void cmb_tabelasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tabelasItemStateChanged
        exibir();
    }//GEN-LAST:event_cmb_tabelasItemStateChanged

    private void bnt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt_editarActionPerformed
        
        try {
            if (indexTbl != -1) {
                form_informacoes informacoes = new form_informacoes(tabelaCmb, "Editando");
                switch (tabelaCmb) {
                    case "Games":
                        informacoes.games.setCodigo(String.valueOf(tbl_tabela.getValueAt(indexTbl, 0)));
                        informacoes.games.setCodigo_barras(String.valueOf(tbl_tabela.getValueAt(indexTbl, 1)));
                        informacoes.games.setCodigo_marca(String.valueOf( tbl_tabela.getValueAt(indexTbl, 2)));
                        informacoes.games.setTitulo(String.valueOf( tbl_tabela.getValueAt(indexTbl, 3)));
                        informacoes.games.setPlataforma(String.valueOf( tbl_tabela.getValueAt(indexTbl, 4)));
                        informacoes.games.setIdiomas(String.valueOf( tbl_tabela.getValueAt(indexTbl, 5)));
                        informacoes.games.setFaixa_etaria(String.valueOf( tbl_tabela.getValueAt(indexTbl, 6)));
                        informacoes.games.setConteudo_embalagem(String.valueOf( tbl_tabela.getValueAt(indexTbl, 7)));
                        informacoes.games.setGenero(String.valueOf( tbl_tabela.getValueAt(indexTbl, 8)));
                        informacoes.games.setCodigo_fornecedor(String.valueOf( tbl_tabela.getValueAt(indexTbl, 9)));
                        informacoes.games.setPreco(String.valueOf( tbl_tabela.getValueAt(indexTbl, 10)));
                        informacoes.games.setAvaliacao(String.valueOf( tbl_tabela.getValueAt(indexTbl, 11)));
                        break;
                    case "Fornecedores":
                        informacoes.fornecedor.setCodigo_fornecedor(String.valueOf(tbl_tabela.getValueAt(indexTbl, 0)));
                        informacoes.fornecedor.setFornecedor(String.valueOf(tbl_tabela.getValueAt(indexTbl, 1)));
                        informacoes.fornecedor.setGarantia_fornecedor(String.valueOf(tbl_tabela.getValueAt(indexTbl, 2)));
                        informacoes.fornecedor.setSac(String.valueOf(tbl_tabela.getValueAt(indexTbl, 3)));
                        informacoes.fornecedor.setCidade(String.valueOf(tbl_tabela.getValueAt(indexTbl, 4)));
                        informacoes.fornecedor.setCeo(String.valueOf(tbl_tabela.getValueAt(indexTbl, 5)));
                        informacoes.fornecedor.setQtdGames(String.valueOf(tbl_tabela.getValueAt(indexTbl, 6)));
                        break;
                    case "Marcas":
                        
                        //As informações da marca não estão sendo exibidas corretamente no formulário ou sendo gravadas no model de forma errada
                        //Talvez criar um método que receba um objeto para gravar no model
                        informacoes.marca.setCodigo_marca(String.valueOf(tbl_tabela.getValueAt(indexTbl, 0)));
                        informacoes.marca.setMarca(String.valueOf(tbl_tabela.getValueAt(indexTbl, 1)));
                        informacoes.marca.setCidade(String.valueOf(tbl_tabela.getValueAt(indexTbl, 2)));
                        informacoes.marca.setTelefone(String.valueOf(tbl_tabela.getValueAt(indexTbl, 3)));
                        informacoes.marca.setQtdGames(String.valueOf(tbl_tabela.getValueAt(indexTbl, 4)));
                        break;
                }
                
                informacoes.editando();
                informacoes.setVisible(true);
                exibir();
                
            } else {
                MessageShow("Selecione a linha na tabela que deseja editar!");
            }
        } catch (Exception e) {
            MessageShow(e.getMessage());
        }
        
    }//GEN-LAST:event_bnt_editarActionPerformed

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        try {
            form_informacoes informacoes = new form_informacoes(tabelaCmb, "Novo");
            informacoes.setVisible(true);
            //this.setVisible(false);
            exibir();
        } catch (Exception e) {
            MessageShow(e.getMessage());
        }
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        try {
            int dialog = JOptionPane.showConfirmDialog(this,"Deseja realmente remover este registro?", "Remover Permanentemente",DISPOSE_ON_CLOSE);
        if (dialog == JOptionPane.YES_OPTION){
            switch(tabelaCmb){
                case "Games":
                    MessageShow(daoGames.removeGames(id));
                    break;
                case "Fornecedores":
                    MessageShow(daoFornecedor.removeFornecedor(id));
                    break;
                case "Marcas":
                    MessageShow(daoMarca.removeMarca(id));
                    break;
            }
        }
        exibir();
        } catch (Exception e) {
            MessageShow(e.getMessage());
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void tbl_tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tabelaMouseClicked
        //ID do atual registro da tabela
        indexTbl = tbl_tabela.getSelectedRow();
        id = (int) tbl_tabela.getValueAt(indexTbl, 0);
    }//GEN-LAST:event_tbl_tabelaMouseClicked

    
    //MÉTODOS//
    
    public void exibir(){
        int indexCmb_tabelas = cmb_tabelas.getSelectedIndex();
        tabelaCmb = cmb_tabelas.getItemAt(indexCmb_tabelas);
        
        switch(tabelaCmb){
            case "Games":
                resultSet = daoGames.getGamesResultSet();
                break;
            case "Fornecedores":
                resultSet = daoFornecedor.getFornecedoresResultSet();
                break;
            case "Marcas":
                resultSet = daoMarca.getMarcaResultSet();
                break;
        }
        
        try {
            tableModel = buildTable(resultSet);
            tbl_tabela.setModel(tableModel);
            
            //Redimensionar o Form
            int tbl_width = tbl_tabela.getSize().width;
            int panel_width = jpa_ferramentas.getSize().width;
            
        } catch (Exception e) {
            MessageShow(e.getMessage());
        }
    }
    
    public int getId(){
        return this.id;
    }
    
    private static DefaultTableModel buildTable(ResultSet resultSet) throws SQLException {
        ResultSetMetaData metaData = resultSet.getMetaData();
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= columnCount; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (resultSet.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                vector.add(resultSet.getObject(columnIndex));
            }
            data.add(vector);
        }
        return new DefaultTableModel(data, columnNames);
    }
    
    public void MessageShow(String text){
        JOptionPane.showMessageDialog(this, text, "Mensagem", JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_editar;
    private javax.swing.JButton btn_adicionar;
    private javax.swing.JButton btn_remover;
    private javax.swing.JComboBox<String> cmb_tabelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel jpa_ferramentas;
    private javax.swing.JTable tbl_tabela;
    // End of variables declaration//GEN-END:variables
}
